export const BUY_LAPTOP="BUY_LAPTOP";
export const BUY_MOBILE="BUY_MOBILE";
export const FETCH_USER_REQUEST = "FEACT_USER_REQUEST";
export const FETCH_SUCCESS_REQUEST = "FEACT_SUCCESS_REQUEST";
export const FETCH_ERROR_REQUEST = "FEACT_ERROR_REQUEST";

